In [1]:
# 通过列表创建一维数组
import numpy as np
np.array([1, 2, 3])  # 数组是一个秩为 1 的数组，因为它只有一个轴，而轴的长度为 3。

array([1, 2, 3])

In [2]:
# 通过列表创建二维数组
np.array([(1, 2, 3), (4, 5, 6)])

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# 创建全为0的二维数组
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
# 创建全为1的三维数组
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [7]:
# full函数，创建任意大小的数组并填充任意数字
np.full((3,4), 2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [8]:
# 创建一维等差数组
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
# 创建二维等差数组
np.arange(6).reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
# 创建单位矩阵（二维数组）
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# 创建二维随机数组
np.random.rand(2,3)

array([[0.4441318 , 0.16862928, 0.84769552],
       [0.6619375 , 0.81685232, 0.85835261]])

In [13]:
# 创建二维随机证书数组（数值小于5）
np.random.randint(5, size = (2,3))

array([[4, 2, 2],
       [3, 4, 0]])

In [14]:
a = np.array([10, 20, 30, 40, 50])
b = np.arange(1, 6)
a,b

(array([10, 20, 30, 40, 50]), array([1, 2, 3, 4, 5]))

In [15]:
# sum加法运算
a = np.array([[1,2],[3,4]])
np.sum(a)

10

In [16]:
# axis = 0 表示对每一列求和
np.sum(a, axis=0)

array([4, 6])

In [17]:
# axis = 1 表示对每一行求和
np.sum(a, axis=1)

array([3, 7])

In [18]:
# 求取平均值
np.mean(a)

2.5

In [19]:
a

array([[1, 2],
       [3, 4]])

In [20]:
# 将数组a变成一行两列
np.tile(a, (1,2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [21]:
np.tile(a, (2,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [23]:
# argsort 将元素按行从小到大排序，返回对应位置元素的下标
a = np.array([[3,6,4,11], [5,10,1,3]])
a.argsort()

array([[0, 2, 1, 3],
       [2, 3, 0, 1]], dtype=int64)

In [26]:
# 以为数组加法运算
a = np.array([10, 20, 30, 40, 50])
b = np.arange(1, 6)
a + b

array([11, 22, 33, 44, 55])

In [27]:
# 一维数组的剑法运算
a - b

array([ 9, 18, 27, 36, 45])

In [28]:
# 一维数组的乘法运算
a * b

array([ 10,  40,  90, 160, 250])

In [29]:
# 一维数组的除法运算
a / b

array([10., 10., 10., 10., 10.])

In [30]:
# 索引的使用
# 取出某个确定的值
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
a[1,2] # 表示第二行，第三列的数。逗号前表示一维，逗号后表示二维，以此类推

7

In [31]:
# 取出某个范围的值
a[-2:, 1:3]  # 冒号表示所取值的范围，跟列表索引用法一样
             # 逗号用来区分每个维度，该代码表示：取倒数第二行到最后一行，第二列到第三列

array([[ 6,  7],
       [10, 11]])

In [32]:
# 给某个范围的数进行运算
a[np.arange(3),1] += 10 # 给a数组的第二列上的每个数加上10 [np.arange(3),1]表示第0，1，2行，第2列
a

array([[ 1, 12,  3,  4],
       [ 5, 16,  7,  8],
       [ 9, 20, 11, 12]])

In [33]:
# 从0开始生成10个数
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# 生成特定范围的数
np.arange(3, 7)

array([3, 4, 5, 6])

In [36]:
# 也可这样写，相当于一个行对应一个列
a[[0,1,2], [1,1,1]] += 10
a

array([[ 1, 32,  3,  4],
       [ 5, 36,  7,  8],
       [ 9, 40, 11, 12]])

In [37]:
# 获取数组中大于或小于某个确定值的数组
result_index = a > 10
result_index

array([[False,  True, False, False],
       [False,  True, False, False],
       [False,  True,  True,  True]])

In [38]:
a[result_index]

array([32, 36, 40, 11, 12])

In [39]:
# 这样写即可
a[a>10]

array([32, 36, 40, 11, 12])

In [40]:
# 使用dtype函数产看数组的数据类型
a = np.array([1,2,3])
a.dtype

dtype('int32')

In [41]:
# 使用astype转换数据类型
a = np.array(['1.2', '1.3', '1.4'], dtype=np.string_)
a

array([b'1.2', b'1.3', b'1.4'], dtype='|S3')

In [42]:
a.astype(np.float)

C:\Users\73479\AppData\Local\Temp\ipykernel_9032\2714328292.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a.astype(np.float)


array([1.2, 1.3, 1.4])